export default {
    "AL": "Alabama",
    "AK": "Alaska",
    "AS": "American Samoa",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District Of Columbia",
    "FM": "Federated States Of Micronesia",
    "FL": "Florida",
    "GA": "Georgia",
    "GU": "Guam",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MH": "Marshall Islands",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "MP": "Northern Mariana Islands",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PW": "Palau",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VI": "Virgin Islands",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
};

export type StatesType = {
    AL: String,
    AK: String,
    AS: String,
    AZ: String,
    AR: String,
    CA: String,
    CO: String,
    CT: String,
    DE: String,
    DC: String,
    FM: String,
    FL: String,
    GA: String,
    GU: String,
    HI: String,
    ID: String,
    IL: String,
    IN: String,
    IA: String,
    KS: String,
    KY: String,
    LA: String,
    ME: String,
    MH: String,
    MD: String,
    MA: String,
    MI: String,
    MN: String,
    MS: String,
    MO: String,
    MT: String,
    NE: String,
    NV: String,
    NH: String,
    NJ: String,
    NM: String,
    NY: String,
    NC: String,
    ND: String,
    MP: String,
    OH: String,
    OK: String,
    OR: String,
    PW: String,
    PA: String,
    PR: String,
    RI: String,
    SC: String,
    SD: String,
    TN: String,
    TX: String,
    UT: String,
    VT: String,
    VI: String,
    VA: String,
    WA: String,
    WV: String,
    WI: String,
    WY: String
};